import { getLoggedInUserSessionValue, currentUrlInfo } from '../utils/utility.jsx';
const messages = {
        WebUrl: currentUrlInfo(),
        API_ROOT : "http://192.168.1.16:2000",
        USERLIST : "userList",
        ORGANIZATION :"gridorganization",
        SYSTEMSETTING :"Systemsetting",
        newMarkerPlot : 60,
        numDeltas : 10,
        delay : 10,
        OK : 200,
        alreadyExist:422,
        Rejected:405,
        Pending:406,
        Deleted:407,
        NotExist:408,
        LinkExpired:1018,
        NoContent : 204,
        REVISIONNO: "1.4.8.19",
        Timeout   : 300,
        SessionExired : "1009",
        EulaAccept    : "Accept",
        is_maintenance : false,
        ORGNAME: localStorage.getItem('Organization'),
        LOGIN: "Login",
        USERNAME: "Username",
        PASSWORD: "Password",
        KEEPMESIGNIN: "Keep me signed in.",
        FORGOTPASSLINK: "Forgot Password?",
        IFORGOTMYPASSWORD : "I forgot my password",
        SIGNUP: "Sign Up",
        DONTHAVEACCOUNT : "Don't have an account? ",
        COPYRIGHTMSG: new Date().getFullYear() + " e-Software Solutions. All rights Reserved.",
        ERR_INVALID_USER_PASSWORD: "Username or Password is incorrect.",
        EULALEGALAGREEMENT: "User Agreement",
        Privacy: "Privacy",
        CONTACTLINK: "Contact",
        GoBack: "GO BACK",
        NoInternetAvailable: "There is an error while loading Google map library, please try reloading the page.",
        WARNKEEPMESIGNIN: "To ensure maximum security, it is not advisable to use this option on public computers.",
        ACCEPTTERMCONDITIONS: "I have read and accept the terms and conditions",
        DEFAULTNAMESTRING: "---",
        SESSIONEXPIRE: "Your session has expired. Click",
        RELOGIN: "to login again",
        LOGINSESSIONEXPIREHEADER: "Session Expired",
        LOGINSESSIONEXPIRE: "Your session has been expired. Please refresh the page",
        LOCKEDACC: "Your account is locked.",
        UNLOCKACCMSG: "Please contact your system administrator to unlock your account.",
        TOCHANGEPSWD: " to change your password.",
        CONTINUE: "CONTINUE",
        BLOCKWARNING: "Your account will be locked after ",
        ATTEMPTTIMES: "  more wrong attempts.",
        ORGEXPIRED: "User Organization has expired.",
        CONTACTSYSTEMADMIN: "Please contact your system administrator.",
        MAXATTEMPT: 5,
        LOCKUSERCODE: 21005,
        INVALIDUSERCODE: 21007,
        PAYMENTPENDING: 20008,
        ENABLECHECKBOX: "Checkbox will be enabled after scrolling through agreement.",
        ACCEPTBTN: "ACCEPT",
        //FORGOT PASSWORD 
        FPASSTYPELABLE: "Please type your username.",
        SESSIONEXPIRED: "sessionExpired",
        _EMAILTRIGGERMESSAGE1 : "Email has been already sent to registered email ID.",
        _EMAILTRIGGERMESSAGE2 : "Please wait for 15 minutes to request again.",
        // GOOGLEMAP CONSTANTS
        overlayLoadingTemplate: '<span class=""></span>',
        NOALARM: "No sensor alarm detected",
        NOFAULT: "No fault detected",
        NONORMALDEVICE: "No device with normal status detected",
        GEOLOCNOTSUPPORTED: "Geolocation is not supported by this browser.",
        REALTIMEMONITER: "Real Time Monitoring",
        MAPTYPEID: "terrain",
        GOOGLEMAPZOOMLEVEL: 18,
       // GOOGLEAPIKEY: "AIzaSyBc9m_7RDyAlkyqza8GEXKz6LPGIfTub1o",
        GOOGLEAPIKEY: "AIzaSyD5H08Z-bZxOxYbyJGby2qEtjD1Zyw5qE8",
        DEFAULTWORKERSTATUS: "Normal",
        TOTALWORKER: "Total Worker",
        ONLINEWORKER: "Online Worker",
        TOTALWORKERS: "Total Workers",
        ONLINEWORKERS: "Online Workers",
        NonCompliance: "Non-Compliance",
        DefaultLat: "39.043757",
        DefaultLong: "-77.488128",
        GREENCLASS: "green",
        REDCLASS: "red",
        ORANGECLASS: "orange",
        BELLSTOP: "STOPPED",
        BELLPLAY: "PLAYING",
        LAT: "Lat:",
        LNG: "Lng:",
        STOP1MIN: 60,
        STOP15MIN: 900,
        STOP30MIN: 1800,
        NOINSTRUMENTCONNECTED: "No Device Connected",
        BELLSILENCEOPTIONS: [{ "id": "1", "value": 0, "label": "Sounds ON" },
        { "id": "2", "value": 60, "label": "Silence  for 1 min" },
        { "id": "3", "value": 900, "label": "Silence  for 15 min" },
        { "id": "4", "value": 1800, "label": "Silence  for 30 min" }],

        // EVENT AND INSTRUMENT CONSTANTS
        refershInterval: 5000,
        headerrefreshinterval: 1000,
        WORKER: "Worker",
        EVENT: "Event",
        Collapse : "Collapse",
        Expand : "Expand",
        REPORTEDAT: "Reported At",
        DURATION: "Duration",
        INSTRUMENT: "Instrument",
        MAPVIEW: 'Map View',
        NODATAAVAIL: "No Data Available.",
        FILTERBYACCOUNT: "Filter By Worker Account",
        FILTERBYUSER: "Filter By User Account",
        FILTERBYSTATUS: "Filter By Status",
        FILTERBYGROUP: "Filter By Group",
        FILTERBYTIME: "Filter By Time",
        FILTERBYPHONEID: "Filter By Phone ID",
        FILTERBYPHONENUMBER: "Filter By Mobile Number",
        SORTBY: "Sort By",
        SORTBYSTATUS: "Sort By Status",
        SERIALNUMBER: "Serial Numbers",
        LASTCOMMUNICATION: "Last Communication",
        PRIMARYGROUP: "Group",
        DEVICE: "Device",
        AssignedInstruments: "Assigned Instruments",
        NEXTBUTTON: "Next",
        PREVIOUSBUTTON: "Previous",
        GRIDHEIGHT: 400,
        //EMAIlINVITE CONSTANT
        SENDTO : "Send To",
        TITLE : "Title",
        STARTDATE : "Start Date",
        ENDDATE : "End Date",
        // ORGANIZATION CONSTANTS
        ORGANIZATIONVARIABLE: "Organization",
        HISTORICALEVENTVARIABLE: "Events Report",
        EULAAGREEMENTVARIABLE: "Eula Agreement",
        ORGANIZATIONS: "Organizations",
        ExistOrganization: "Organization already exists",
        NOINSTRUMENT: "No instrument Assigned",
        RESPONSEMESSAGE: "Response Message",
        ORGANIZATIONADD: "New organization created successfully.",
        DELETEORGANIZATIONHEADER: "Delete Organization",
        DELETETORGANIZATIONBODY: "Do you want to delete",
        ORGANIZATIONMSG: "organization?",
        USERGROUP: "Group?",
        ORGDELETESUCCESS: "Organization deleted successfully.",
        USERGROUPSUCCESS: "Group deleted successfully.",
        ORGUPDATE: "Organization updated successfully.",
        SSUPDATE: "System Settings updated successfully.",
        Address: "Address",
        CONTACTPERSON: "Contact Person",
        EMAIL: "Email",
        Emails : "Emails",
        EMAILERROR: "Invalid email, try like \"user@domain.com\"",
        PHONE: "Phone",
        PHONENUMBER : "Phone Number",
        ACTIONS: "Actions",
        CANCEL: "CANCEL",
        SAVE: "SAVE",
        SUBMITBTN: "Submit",
        CITY: "City",
        PURCHASEORDER: "Purchase Order Number",
        EXPIRYDATE: "Date Of Expiration *",
        EXPDATEERROR: "Should be greater than current date",
        LICENCSE: "Allocated Licenses * ",
        USERCOUNT: "Available Licenses",
        ERRALLOCATELICENCSES: "Cannot be less than used licenses",
        STATE: "State/Province",
        COUNTRY: "Country/Region",
        WEBSITE: "Website",
        POSTALZIPCODE: "Postal/ZIP Code",
        ZIPCODE : "Zip/Postal Code",
        UPDATEORGANIZATION: "Update Organization",
        AddOrganization: "Add Organization",
        USERASSIGNEDSUCCESSMSG: "Selected user assigned successfully.",
        STRING: "String",
        HONEYWELLINTERNALINFO: "Honeywell Internal Information",
        COMPANYINFO: "Company Detail",
        CONTECTPERSONINFO: "Contact Person Detail",
        MAXLICENSES: 3000,
        COUNTRYUSNAME: "USA (United States of America)",
        ORGEXPIRYDATE: "Expiry Date",
        JUMPTOLBL: "Jump To",
        ORGEXPORT : "Export Organizations",
        TAKETIMETOORGCSV: "It will take some time depending upon total number of organizatins.",
        // USERMANAGEMENT CONSTANTS
        USERDELETEHEADER: "Delete User",
        LOADMOREBTN: "LOAD MORE",
        ADDUSER: "New user created successfully.",
        ADDUPDATEUSERLINK : "addupdateUser",
        SMARTPHONELINK : "smartPhone",
        DELETEUSERSUCCESS: "User deleted successfully.",
        USERDELETE: "User?",
        USERUPDATE: "User updated successfully.",
        USERGROUPUPDATE: "Group added successfully.",
        USERNOTADDED: "User can not be added.",
        INVALIDFILE: "Invalid File",
        SIZEFILE: "File size can not be greater than 1MB. Supported file formats[jpg,png,jpeg]",
        CHANGEPASSWORDMSG: "Reset password link has been sent to the registered email id.",
        PROCESSING: "Processing",
        LOADINGIMG: document.querySelector("#loading-block"),
        MODELVIEWDIV: document.querySelector("#modelview"),
        MOdelSinupSuccess: "Registration completed. Please login to continue.",
        EmailSent: "An email has been sent to you with user name and password.",
        MOdelSinupError:"There is some error, please try after some time.",
        timeOutSec: 0,
        USERMANAGENENT: "User Management",
        EMAILINVITE: "Email Invite List",
        USERVARIABLE: "User",
        USERVARIABLES: "Users",
        USERGROUPVARIABLES: "Total Users groups",
        UserId: "User Id",
        OrganizationName: "Organization Name",
        Organization: "Organization",
        Mobile: "Mobile",
        Comment: "Comment",
        Reason: "Reason",
        AllowDataUpload: "Allow Data Upload",
        DCPrivilege: "DC Privilege",
        UpdateUser: "Update User",
        AddUserLabel: "Add User",
        FirstName: "First Name",
        MiddleName: "Middle Name",
        LastName: "Last Name",
        UserEmail: "Email",
        EMAILID : "Email Id",
        Username: "User ID",
        NickName: "Nick Name",
        MobileNumber: "Mobile Number",
        CompanyName: "Company Name",
        Password: "Password",
        ConfirmPassword: "Confirm Password",
        Department: "Department",
        Roles: "Roles",
        ROLEOFUSER: "Role",
        Group: "Group",
        Back: "Back",
        USERLISTCOOKIES : "userListCookies",
        USERACCOUNTCOOKIES : "userAccountCokkies",
        Mandatory: "*",
        LICENSEUSERFULLMSG : "You have used all of your available Worker Licenses. Please contact prgsupport@honeywell.com / 1800400000 for additional licenses.",
        TIMEOUTMESSAGE: "After 1 more minute of inactivity, you will be automatically logged out.",
        INSTRUMENTSORTINGJSON: [{ "id": "0", "sortOrder": "asc", "sortColumn": "selectedWorker", "value": "Workerasc", "label": "Worker  -  Ascending" },
        { "id": "1", "sortOrder": "des", "sortColumn": "selectedWorker", "value": "Workerdes", "label": "Worker  -  Descending" },
        { "id": "2", "sortOrder": "asc", "sortColumn": "SerialNumber", "value": "SerialNumberasc", "label": "Serial Numbers  -  Ascending" },
        { "id": "3", "sortOrder": "des", "sortColumn": "SerialNumber", "value": "SerialNumberdes", "label": "Serial Numbers  -  Descending" },
        { "id": "4", "sortOrder": "asc", "sortColumn": "EventReportTime", "value": "EventReportTimeasc", "label": "Last Communication  -  Ascending" },
        { "id": "5", "sortOrder": "des", "sortColumn": "EventReportTime", "value": "EventReportTimedes", "label": "Last Communication  -  Descending" },
        { "id": "6", "sortOrder": "asc", "sortColumn": "Instrument", "value": "Instrumentasc", "label": "Device  -  Ascending" },
        { "id": "7", "sortOrder": "des", "sortColumn": "Instrument", "value": "Instrumentdes", "label": "Device  -  Descending" }],
        INSTRUMENTFILTERJSON: [{ "id": "1", "value": "Alarm", "label": "Alarm" },
        { "id": "2", "value": "Fault", "label": "Fault" },
        { "id": "3", "value": "Online", "label": "Online" },
        { "id": "4", "value": "Offline", "label": "Offline" }],
        EVENTSORTINGJSON: [{ "id": "0", "sortOrder": "asc", "sortColumn": "selectedWorker", "value": "Workerasc", "label": "Worker  -  Ascending" },
        { "id": "1", "sortOrder": "des", "sortColumn": "selectedWorker", "value": "Workerdes", "label": "Worker  -  Descending" },
        { "id": "2", "sortOrder": "asc", "sortColumn": "Events", "value": "Eventrasc", "label": "Event  -  Ascending" },
        { "id": "3", "sortOrder": "des", "sortColumn": "Events", "value": "Eventdes", "label": "Event  -  Descending" },
        { "id": "4", "sortOrder": "asc", "sortColumn": "EventReportTime", "value": "EventReportTimeasc", "label": "Reported At  -  Ascending" },
        { "id": "5", "sortOrder": "des", "sortColumn": "EventReportTime", "value": "EventReportTimedes", "label": "Reported At  -  Descending" },
        { "id": "6", "sortOrder": "asc", "sortColumn": "Organization", "value": "Organizationasc", "label": "Organization  -  Ascending" },
        { "id": "7", "sortOrder": "des", "sortColumn": "Organization", "value": "Organizationdes", "label": "Organization  -  Descending" },
        { "id": "8", "sortOrder": "asc", "sortColumn": "Instrument", "value": "Instrumentasc", "label": "Instrument  -  Ascending" },
        { "id": "9", "sortOrder": "des", "sortColumn": "Instrument", "value": "Instrumentdes", "label": "Instrument  -  Descending" }],
        EVENTFILTERJSON: [{ "id": "1", "value": "Alarm", "label": "Alarm" },
        { "id": "2", "value": "Fault", "label": "Fault" }],
        USERLISTSORTINGJSON: [{ "id": "0", "sortOrder": "asc", "sortColumn": "User Id", "value": "userasc", "IsAscOrder": "true", "OrderID": "1", "label": "User  -  Ascending" },
        { "id": "1", "sortOrder": "des", "sortColumn": "User Id", "value": "userdesc", "IsAscOrder": "false", "OrderID": "1", "label": "User  -  Descending" },
        // {"id":"2",	"sortOrder":"asc",	"sortColumn":"Organization_Name", 	"value":"orgasc",   "IsAscOrder":"true",  "OrderID":"2",		"label":"Organization Name  -  Ascending"},
        // {"id":"3",	"sortOrder":"des",	"sortColumn":"Organization_Name", 	"value":"orgdesc",  "IsAscOrder":"false",  "OrderID":"2",		"label":"Organization Name  -  Descending"},
        { "id": "4", "sortOrder": "asc", "sortColumn": "Mobile", "value": "mobileasc", "IsAscOrder": "true", "OrderID": "3", "label": "Mobile Number -  Ascending" },
        { "id": "5", "sortOrder": "des", "sortColumn": "Mobile", "value": "mobiledesc", "IsAscOrder": "false", "OrderID": "3", "label": "Mobile Number -  Descending" },
        { "id": "6", "sortOrder": "asc", "sortColumn": "Email", "value": "emailasc", "IsAscOrder": "true", "OrderID": "4", "label": "Email  -  Ascending" },
        { "id": "7", "sortOrder": "des", "sortColumn": "Email", "value": "emaildesc", "IsAscOrder": "false", "OrderID": "4", "label": "Email  -  Descending" }],
        DEPARTMENTLISTJSON: [{ "id": "1", "value": "Industrial Hygienic", "label": "Industrial Hygienic" },
        { "id": "2", "value": "Safety Management", "label": "Safety Management" }],
        SESSIONTIMEOUTOPTIONS: [{ "id": 0, "value": "Never", "label": "Never" },
        { "id": 300, "value": "5m", "label": "5 minutes" },
        { "id": 900, "value": "15m", "label": "15 minutes" },
        { "id": 1800, "value": "30m", "label": "30 minutes" },
        { "id": 3600, "value": "60m", "label": "60 minutes" }],
        DATEFORMATOPTIONS: [{ "id": 0, "value": "MM-dd-yyyy", "label": "MM-dd-yyyy" },
        { "id": 1, "value": "dd-MM-yyyy", "label": "dd-MM-yyyy" },
        { "id": 2, "value": "yyyy-MM-dd", "label": "yyyy-MM-dd" }],
        TIMEFORMATOPTIONS: [{ "id": 0, "value": 'HH:MM:ss AM/PM (12Hours)', "label": "HH:MM:ss AM/PM (12 Hours)" },
        { "id": 1, "value": 'HH:MM:ss AM/PM (24Hours)', "label": "HH:MM:ss AM/PM (24 Hours)" }],
        Radiations: [{ "id": "0", "value": "µR/h", "label": "µR/h" },
        { "id": "1", "value": "µSv/h", "label": "µSv/h" }],
        PASSWORDEXPIRYOPTIONS: [{ "id": "0", "value": "60", "label": "60" },
        { "id": "1", "value": "90", "label": "90" },
        { "id": "2", "value": "180", "label": "180" },
        { "id": "3", "value": "365", "label": "365" },
        { "id": "4", "value": "0", "label": "Never" }
        ],
        WindSpeed: [{ "id": "0", "value": "m/sec", "label": "m/sec" },
        { "id": "1", "value": "Km/h", "label": "Km/h" },
        { "id": "2", "value": "mph", "label": "mph" }],
        Temperature: [{ "id": "0", "value": "°F", "label": "°F" },
        { "id": "1", "value": "°C", "label": "°C" }],
        WORKERSORTINGJSON: [{ "id": "0", "sortOrder": true, "sortColumn": "1", "value": "Nameasc", "label": "Worker - Ascending" },
        { "id": "1", "sortOrder": false, "sortColumn": "1", "value": "Namedes", "label": "Worker - Descending" },
        { "id": "2", "sortOrder": true, "sortColumn": "2", "value": "Groupasc", "label": "Group - Ascending" },
        { "id": "3", "sortOrder": false, "sortColumn": "2", "value": "Groupdes", "label": "Group - Descending" },
        { "id": "4", "sortOrder": true, "sortColumn": "3", "value": "Statusasc", "label": "Status - Ascending" },
        { "id": "5", "sortOrder": false, "sortColumn": "3", "value": "Statusdes", "label": "Status - Descending" },
        ],
        WORKERFILTERJSON: [{ "id": "5", "filterBy": "100", "value": "PanicAlarm", "label": "Panic Alarm" },
        { "id": "4", "filterBy": "80", "value": "Mandown", "label": "Mandown" },
        { "id": "3", "filterBy": "60", "value": "Alarm", "label": "Alarm" },
        { "id": "2", "filterBy": "40", "value": "NonCompliance", "label": "Non Compliance" },
        { "id": "1", "filterBy": "20", "value": "Fault", "label": "Fault" },
        { "id": "0", "filterBy": "0", "value": "Normal", "label": "Normal" }],
        WORKERFILTERJSONR: [{ "id": "5", "filterBy": "100", "value": "PanicAlarm", "label": "Panic Alarm" },
        { "id": "4", "filterBy": "80", "value": "Mandown", "label": "Mandown" },
        { "id": "3", "filterBy": "60", "value": "Alarm", "label": "Gas Alarm(s)" },
        { "id": "2", "filterBy": "40", "value": "NonCompliance", "label": "Non Compliance" },
        { "id": "1", "filterBy": "20", "value": "Fault", "label": "Fault(s)" },
        { "id": "0", "filterBy": "0", "value": "Normal", "label": "Normal" }],
        WORKEREVENTFILTERJSON: [{ "id": "5", "filterBy": "100", "value": "PanicAlarm", "label": "Panic Alarm" },
        { "id": "4", "filterBy": "80", "value": "Mandown", "label": "Mandown" },
        { "id": "3", "filterBy": "60", "value": "Alarm", "label": "Alarm" },
        { "id": "2", "filterBy": "40", "value": "NonCompliance", "label": "Non Compliance" },
        { "id": "1", "filterBy": "20", "value": "Fault", "label": "Fault" }],
        WORKEREVENTFILTERJSONR: [{ "id": "5", "filterBy": "100", "value": "PanicAlarm", "label": "Panic Alarm" },
        { "id": "4", "filterBy": "80", "value": "Mandown", "label": "Mandown" },
        { "id": "3", "filterBy": "60", "value": "Alarm", "label": "Gas Alarm(s)" },
        { "id": "2", "filterBy": "40", "value": "NonCompliance", "label": "Non Compliance" },
        { "id": "1", "filterBy": "20", "value": "Fault", "label": "Fault(s)" }],
        WORKERTIMEFILTERJSON: [/*{ "id": "0", "value": 300, "label": "Now" },*/
		{ "id": "1", "value": 86400, "label": "Last 24 Hours" },
        { "id": "2",  "value": 604800, "label": "Last 7 days" },
        { "id": "3", "value": 2592000, "label": "Last 30 days" }],
        SCUSERSESSIONTIMEOUTOPTIONS: [{ "id": "0", "value": "Never", "label": "Never" },
        { "id": "1", "value": "1hr", "label": "1 Hour" },
        { "id": "8", "value": "8hr", "label": "8 Hours" },
        { "id": "24", "value": "24hr", "label": "24 Hours" }],
        Last24Hours : "Last 24 Hours",
        Last24HoursArray : { "id": "1", "value": 86400, "label": "Last 24 Hours" },
        UPDATE: "Update",
        DELETE: "Delete",
        APPROVE : "Approve",
        UNAPPROVE : "Un-Approve",
        DECLINE : "Deny",
        ASSIGNUSER: "Assign User",
        ACTION: "Action",
        ResetFilters : "Reset Filters",
        CHANGEPASSWORD: "Change Password",
        RESETPASSWORD: "Reset Password",
        ASSIGNINSTRUMENT: "Assign Instrument",
        ASSIGNINSTRUMENTS: "Assign Instruments",
        INDIVIDUALREPORT: "Create Individual Physiological Monitor Report",
        PHONEASSIGNMENTHISTORY: "Phone Assignment History",
        ORGANIZATION: "",
        USER: "administrator",
        ID: 0,
        ROLE: "1",
        ERROR: "Error",
        UserExist: "User already exist",
        UserNotExist: "Username does not exist.",
        INPUTPARAMETER: "Input parameters are not in correct format.",
        SERACHWORKERINST: "Search Online Workers",
        ALLORGANISATION: "all organization",
        ALLORGANISATIONName : "All organization",
        DEFAULT: "Default",
        ASSIGNEDDATE: "Assigned Date",
        UNASSIGNEDDATE: "Unassigned Date",
        EN: "en",
        ADMINISTRATOR: "administrator",
        NA: "N/A",
        USERFULLNAME: "USERNAME",
        WAITINGMSG: "Please wait while PDF is generated.",
        TAKETIME: "It will take some time depending upon total number of phone assignments.",
        DONTCLOSE: 'Please do not close or refresh the page, or press the browser "Back" button.',
        CSVWAITINGMSG: "Please wait while CSV is being generated.",
        GENERATED: "has been generated successfully.",
        PLEASECLICK: "Please click",
        PLEASE : "Please",
        PDF: "PDF",
        CSV: "CSV",
        TODOWNLOAD: "to download",
        HERE: "here",
        ClickHere : "Click here",
        ERRORINGENERATING: "Error in generating",
        EXPORTCSV: "Export to CSV",
        EXPORTPDF: "Export to PDF",
        /* LEGAL AGREEMENT CONSTANT */
        LegalAgreementRevisionNo: "Legal Agreement Revision No.",
        PHONEIMEINO: "Phone IMEI No.",
        ACCEPTANCEDATE: "Acceptance Date",
        TAKETIMEFOREVENTS: "It will take some time depending upon total number of Events.",
        TAKETIMEFORLEGALAGREE: "It will take some time depending upon total number of legal agreement.",
        LEGALAGREEMENTPOPUPHEADE: "Safety Communicator Legal Agreement Acceptance History",
        LEGALAGREEMENTHISTORY: "Legal Agreement Acceptance History",
        EMAILNOTEXIST: "No email id associated with ",
        USERTXT: "user",
        //SYSTEMS SETTINGS SCROLL SPY CONSTANTS
        CHECKPARAMETERS: "Please check all input parameters.",
        VALIDATIONSELECTPAYMENTOPTION: "Please select at least one account type.",
        SYSTEMSETTINGUPDATEDSUCCESSFULLY: "System settings updated successfully.",
        SESSIONTIMEOUT: "Session Timeout",
        PRGSESSIONTIMEOUTLBL : "ProRAE Guardian",
        SCSESSIONTIMEOUTLBL : "Safety Communicator",
        SESSIONLOGOUTHEADERMSG: "Logged Out",
        SESSIONLOGOUTBODYMSG: "Session timed out. Please Click ",
        LOCALESETTINGS: "Time Settings",
        EMAILSETTING: "Email Settings",
        PASSWORDPOLICY: "Password Policy",
        USERGROUPS: "User Groups",
        PHYSIOLOGICALMONITOR: "Physiological Monitor Settings",
        REMOTEACCESSPOLICY: "Remote Access Policy",
        COMMUNICATIONSETTING: "Communication Settings",
        ACCOUNTLOCKPOLICY: "Account Lockout Policy",
        SCANNINGKIOSK: "Scanning Kiosk",
        SS_DEVICEINFORMATIONVIEW: "Records In Device Information View",
        SS_DATADISPLAY: "Data Display",
        SS_DATETIME: "Date/Time Format",
        SS_GPSFORMAT: "Gps Format",
        SS_MEASUREMENT: "Measurement Unit",
        UNDO: "UNDO CHANGES",
        REVISION: "Revision",
        LEGALEMAILACCOUNT:"Legal Email Account",
        LEGALEMAILACCOUNTS:"Legal Email Accounts",
        SS_COUNTRY:"Country",
        //SYSTEMS SETTINGS : COMMUNICATION SETTINGS :START
        SS_ICOMMUNICATIONINTERVAL: "Instrument Communication Interval (sec)",
        SS_ICOMMUNICATIONTIMEOUT: "Instrument Communication Timeout (sec)",
        SS_ICONNECTIONTIMEOUT: "Instrument Connection Timeout (sec)",
        SS_PRGCOMMUNICATIONINTERVAL: "ProRAE Guardian Communication Interval (sec)",
        SS_PRGCOMMUNICATIONTIMEOUT: "ProRAE Guardian Communication Timeout (sec)",
        SS_PRGCONNECTIONTIMEOUT: "ProRAE Guardian Connection Timeout (sec)",
        SS_COMMUNICATIONTEMPRATURELable: "Temperature",
        SS_COMMUNICATIONTEMPRATURE: [{ "id": "0", "value": "0", "label": "Fahrenheit" },
        { "id": "1", "value": "1", "label": "Celsius" }],
        SS_ERRORPRGCOMMUNICATION: "Should be 3 times of ProRAE Guardian Communication Interval",
        SS_ERRORINSTCOMMUNICATION: "Should be 3 times of Instrument Communication Interval",
        //SYSTEMS SETTING : ACCOUNT LOCK POLICY
        SS_NUMBERINVALIDATTEMPTSLABEL: "Select Number of Invalid Attempts",
        SS_NUMBERINVALIDATTEMPTS: [{ "id": "2", "value": "2", "label": "2 Attempts" },
        { "id": "5", "value": "5", "label": "5 Attempts" },
        { "id": "8", "value": "8", "label": "8 Attempts" },
        { "id": "10", "value": "10", "label": "10 Attempts" }],
        SS_LOCKOUTDURATIONLABEL: "Select Lockout Duration",
        SS_LOCKOUTDURATIONS: [{ "id": "300", "value": "300", "label": "5 Minutes" },
        { "id": "900", "value": "900", "label": "15 Minutes" },
        { "id": "1800", "value": "1800", "label": "30 Minutes" },
        { "id": "3600", "value": "3600", "label": "1 Hour" }],
        //SYSTEMS SETTING : SCANNING KIOSK
        SS_ALLOWINSTUMENTWORKERASSOCIATION: "Allow multiple instrument's association with worker ( Upto 5 Instruments)",
        SS_ALLOWALLWORKERS: "Allow all worker's",
        SS_ALLOWALLINSTRUMENTS: "Allow all instrument's",
        SS_AlLOWEDTIMEASSIGNMENTLABEL: "Time allowed to assign instrument. (In seconds)",
        SS_ALLOWEDTIMEASSIGNMENT: [{ "id": "5", "value": "5", "label": "5" },
        { "id": "10", "value": "10", "label": "10" },
        { "id": "20", "value": "20", "label": "20" },
        { "id": "30", "value": "30", "label": "30" }],
        // SYSTEMS SETTING PASSWORD POLICY CONSTANTS
        SS_WEAK: "Weak",
        SS_MEDIUM: "Medium",
        SS_STRONG: "Strong",
        SS_WEAK_MESSAGE: "Password must contain a minimum of 8 characters.",
        SS_MEDIUM_MESSAGE: "Password must contain a minimum of 8 characters, at least one lowercase letter, one uppercase letter , one numeric digit, and optional special character: !@#$%^*()",
        SS_STRONG_MESSAGE: "Password must contain a minimum of 8 characters, at least one lowercase letter, one uppercase letter, one numeric digit, and one special character: !@#$%^*()",
        // SYSTEMS SETTING REMOTE ACCESS POLICY CONSTANTS
        SS_REMOTEACCESSPOLICY: " Authorization is required for Safety Communicator devices to access this ProRAE Guardian.",
        device_sensor_fault_status: ["Wait", "Unit Fail", "Memory", "Battery", "Pump/Fan", "ROG Invalid", "ROG Warning", "ROG Alarm", "ROG Unknown", "Fail", "Lamp", "Off", "Short", "Broken"],
        device_sensor_alarm_status: ["Hi High", "Lo Low", "Dose", "Alarm", "Ovr", "MAX", "Max", "High", "Low", "STEL", "TWA", "NEG", "Medium"],
        DEVICE_NON_COMPLIANCE: ["CalDue", "CAL", "Cal", "Bump", "BumpDue"],
        MANDOWN_STATUS_ALARM: ["Mandown Warning", "Mandown Alarm", "Super Alarm"],

        //System Setting PhysiologicalMonitor constants
        SS_HEARTRATE: "Heart Rate",
        SS_RESPIRATORY: "Respiratory Rate",
        SS_COREBODY: "Core Body Temp",
        SS_ACTIVITY: "Activity Level",
        SS_POSTURE: "Posture",
        SS_HEARTRATEUNIT: "bpm",
        SS_RESPIRATORYUNIT: "bpm",
        SS_COREBODYUNIT: "DegC",
        SS_ACTIVITYUNIT: "g",
        SS_POSTUREUNIT: "Deg",
        SS_ALARMHIGH: "Alarm High",
        SS_ALARMLOW: "Alarm Low",
        SS_WARNINGHIGH: "Warning High",
        SS_WARNINGLOW: "Warning Low",
        SS_OTHER: "Other Settings",
        SS_AGE: "Age",
        PROFILE: "Profile",
        PROFILEOPTIONS: [{ "id": "0", "value": "Atheletic", "label": "Athletic" },
        { "id": "1", "value": "Very Active", "label": "Very Active" },
        { "id": "2", "value": "Moderately Active", "label": "Moderately Active" },
        { "id": "3", "value": "Activity Compromised", "label": "Activity Compromised" },
        ],
        SS_ALLOWINDIVIDUAL: "Allow Individual Users to Override Default Values",
        SS_AUTHENTICATION: "Enable Authentication",
        SS_RADIATIONS: "Radiation",
        SS_PASSEXPIRY: "Renew Password (Days)",
        SS_WIND: "Wind Speed",
        SS_TEMPERATURE: "Temperature",
        //SYSTEMS SETTINGS - EMAIL GENERAL SETTINGS : START
        SS_SENDEREMAIL: "Sender Email",
        SS_SENDERPASSWORD: "Sender Password",
        SS_SENDERSUBJECT: "Subject",
        SS_SENDERMSG: "Message",
        SS_EMAILSERVPROVIDER: "Email Service Provider",
        SS_YAHOO: "Yahoo",
        SS_GMAIL: "Gmail",
        SS_OTHEREMAIL: "Other",
        SS_SMTPSERVERSETTING: "SMTP Server Settings",
        SS_HOST: "Host",
        SS_PORT: "Port",
        SS_REQUIREDSSL: "Required SSL",
        SS_EMAILVALIDATOR: "Validate Email",
        SS_HOSTYAHOO: "smtp.mail.yahoo.com",
        SS_PORTYAHOO: "465",
        SS_SY: "yes",
        SS_HOSTGMAIL: "smtp.gmail.com",
        SS_PORTGMAIL: "465",
        SS_SG: "yes",
        SS_TOTALUSERGROUP: "Total User Groups",
        SS_TOTALLEGALACCOUNT: "Total Legal Email Accounts",
        //SYSTEMS SETTINGS - EMAIL GENERAL SETTINGS : END
        //SYSTEMS SETTINGS - AGREEMENT CONSTANTS
        UPLOADEDON : "Uploaded On",
        UPLOADEDBY : "Uploaded By",
        Type       : "Type",
        VERSIONNO  : "Version Number",
        SS_ADDUSERAGREEMENT: "Add Agreement",
        SS_UPDATEUSERAGREEMENT: "Update Agreement",
        SS_VIEWUSERAGREEMENT: "View Agreement",
        SS_USERAGREEMENTUPDATE : "Agreement Update",
        SS_TOTALUSERAGREEMENT: "Total Agreements",
        SS_ADDAGREEMENT_SUCCESS: "Agreement added successfully.",
        SS_UPDATEAGREEMENT_SUCCESS: "Agreement updated successfully.",
        AGREEMENTTYPEOPTIONS: [{ "id": "0", "value": "UserAgreement", "label": "User Agreement" },
        { "id": "1", "value": "DataprivacyStatement", "label": "Data Privacy Statement" },
        { "id": "2", "value": "GeoLocation", "label": "Geo Location" }],
        SS_SELECTTYPE  :  "Select Type",
        SS_SELECTLANGUAGE  :  "Select Language",
        DOCUMENTREVISION  :  "Revision Number *",
        agreementFileSize       : "File size should be in PDF format and greater than 0 KB and less than 2 MB",
        UploadAgreement         : "Upload Agreement",
        SelectFile : "Select File",
        DocumentsTypeJSON: [{ "id": "0", "value": "Unknown"},
        { "id": "1", "value": "EULA"},
        { "id": "2", "value": "License Subscription"},
        //{ "id": "3", "value": "Data Privacy Exhibit"},
        { "id": "4", "value": "Data Privacy"},
        { "id": "5", "value": "Geo-location"},
        { "id": "6", "value": "Data Privacy"},
        { "id": "7", "value": "Geo-location"}],
        SUPERADMINAGREEMENTTYPEJSON: [{ "id": "0", "value": "Unknown"},
        { "id": "1", "value": "User Agreement"},
        { "id": "2", "value": "License Subscription"},
        //{ "id": "3", "value": "Data Privacy Exhibit"},
        { "id": "4", "value": "Data Privacy Statement"},
        { "id": "5", "value": "Geo-location Agreement"},
        { "id": "6", "value": "Data Privacy Statement"},
        { "id": "7", "value": "Geo-location Agreement"}],
        SUPERADMINAGREEMENTTYPEARRAYLIST: [
                { "id": "1", "value": "UserAgreement","label":"User Agreement"},
                { "id": "2", "value": "LicenseSubscription" ,"label":"License Subscription"},
                //{ "id": "3", "value": "DataPrivacyExhibit" ,"label":"Data Privacy Exhibit"},
                { "id": "4", "value": "DataPrivacyStatement" ,"label":"Data Privacy Statement"},
                { "id": "5", "value": "GeolocationAgreement" ,"label":"Geo-location Agreement"}],
        ORGADMINAGREEMENTTYPEJSON : [{ "id": "6", "value": "Data Privacy Statement"},
        { "id": "7", "value": "Geolocation Agreement"}],
        ORGADMINAGREEMENTTYPEARRAYLIST : [{ "id": "6", "value": "DataPrivacyStatement","label":"Data Privacy Statement"},
        { "id": "7", "value": "GeolocationAgreement","label":"Geo-location Agreement"}],
        TABINDEXARRAY: [
        { "id": "1","tabIndex": "0", "valuelbl": "User Agreement" },
        { "id": "2","tabIndex": "1", "valuelbl": "License Subscription"},
        //{ "id": "3","value": "2", "valuelbl": "Data Privacy Exhibit"},
        { "id": "4","tabIndex": "2", "valuelbl": "Data Privacy Statement"},
        { "id": "5","tabIndex": "3", "valuelbl": "Geolocation Agreement"},
        { "id": "6","tabIndex": "2", "valuelbl": "Data Privacy Statement"},
        { "id": "7","tabIndex": "3", "valuelbl": "Geolocation Agreement"}],
        TABINDEXFINDVAL: [
                { "id": "0","value": "1", "valuelbl": "User Agreement" },
                { "id": "1","value": "2", "valuelbl": "License Subscription"},
                //{ "id": "2","value": "3", "valuelbl": "Data Privacy Exhibit"},
                { "id": "2","value": "4", "valuelbl": "Data Privacy Statement"},
                { "id": "3","value": "5", "valuelbl": "Geolocation Agreement"}],
        //SYSTEMS SETTINGS - EMAIL SETTINGS : START
        SS_ADDEMAILTEMPLATE: "Add Email Template",
        SS_EMAILNAME: "Name",
        //SYSTEMS SETTINGS - SMS TEMPLATE SETTINGS : START
        SS_CONTENT: "Content",
        SS_SMSTEMPLATE: "SMS Template",
        SS_DELETESMS_SUCCESS: "SMS Template removed successfully.",
        SS_ADDSMS_SUCCESS: "SMS Template added successfully.",
        SS_UPDATESMS_SUCCESS: "SMS Template updated successfully.",
        SS_ADDUSERSMS: "Add SMS Template",
        SS_UPDATEUSERSMS: "Update SMS Template",
        SS_DELETESMSHEADER: "Remove SMS Template",
        SS_DELETESMS_MESSAGE: "Remove the SMS Template named ",
        SS_TOTALSMS: "Total SMS Template",
        //SYSTEMS SETTINGS - SMS CONFIGURATION SETTINGS : START
        SS_SMSCONFIGURATION: "SMS Configuration",
        SS_DELETESMSCONFIGURATION_SUCCESS: "SMS Configuration removed successfully.",
        SS_ADDSMSCONFIGURATION_SUCCESS: "SMS Configuration added successfully.",
        SS_UPDATESMSCONFIGURATION_SUCCESS: "SMS updated successfully.",
        SS_ADDUSERSMSCONFIGURATION: "Add SMS Configuration",
        SS_UPDATEUSERSMSCONFIGURATION: "Update SMS Configuration",
        SS_DELETESMSCONFIGURATIONHEADER: "Remove SMS Configuration",
        SS_DELETESMSCONFIGURATION_MESSAGE: "Remove the SMS Configuration named ",
        SS_TOTALSMSConfiguration: "Total SMS Configuration",
        SS_TEMPLATE  :  "Template",
        // SYSTEM SETTING USER GROUP CONSTANTS
        SS_GROUPNAME: "Group name*",
        SS_GROUPDESCRIPTION: "Description",
        SS_ADDUSERGROUP: "Add Group",
        SS_UPDATEUSERGROUP: "Update Group",
        SS_DELETEGROUPHEADER: "Remove Group",
        SS_ADDLEGALACCOUNT: "Add Legal Email Account",
        SS_UPDATELEGALACCOUNT: "Update Legal Email Account",
        SS_DELETELEGALACCOUNT: "Delete Legal Email Account ",
        SS_DELETEGROUP_MESSAGE: "Remove the group named ",
        SS_DELETELEGALACCOUNT_MESSAGE: "Delete Legal Email Account named ",
        SS_DELETEGROUP_SUCCESS: "Group removed successfully.",
        SS_DELETELEGALACCOUNT_SUCCESS: "Legal Email Account deleted successfully.",
        SS_ADDGROUP_SUCCESS: "Group added successfully.",
        SS_UPDATEGROUP_SUCCESS: "Group updated successfully.",
        SS_ADDLEGALACCOUNT_SUCCESS: "Legal Email Account added successfully.",
        SS_UPDATELEGALACCOUNT_SUCCESS: "Legal Email Account updated successfully.",
        SS_ACCOUNTEXISTS: "Legal Email Account already exists!",
        SS_ACCOUNTEXISTSFORCOUNTRY: "Legal Email Account already exists for this country",
        GroupName: "Group Name",
        SS_GROUPEXISTS: "Group name already exists! Please choose a different group name.",
        //SYSTEMS SETTINGS - EMAIL TEMPLATE SETTINGS
        SS_TOTALTEMPLATE: "Total Email Template",
        SS_GENERALSETTING: "General Settings",
        SS_EMAILTEMPLATE: "Email Template",
        // SMARTPHONE CONSTANTS
        SMARTPHONE: "Smart Phone",
        SMARTPHONES: "Smart Phones",
        TOTALSMARTPHONE: "Total Smart Phones",
        Firstcommunication: "First communication",
        SelectAll: "Select All",
        PhoneId: "Phone ID",
        PHONEID: "Phone ID *",
        SmartPhoneType: "Smart Phone Type",
        FIRSTCOMMDATE: "First Communication",
        LastcommDate: "Last Communication",
        SIMCRDID: "SimCard ID",
        UPDATESMARTPHONE: "Update Smart Phone ",
        AUTHORIZE: "Authorize",
        ADDSMARTPHONE: " Add Smart Phone",
        UPDATEVARIABLE: "UPDATE",
        NOTQUALIFIED: "De-authorize",
        DeviceQUALIFIED: "Device is authorized",
        DeviceNOTQUALIFIED: "Device is not authorized",
        OSVersion: "OS Version",
        SMARTPHONEDELETEHEADER: "Delete Smart Phone",
        SMARTPHONEDELETEBODYMSG: "Smart Phone",
        SMARTPHONEADDSUCCESS: "Smart Phone added successfully.",
        SMARTPHONEUPDATEDSUCCESS: "Smart Phone updated successfully.",
        DELETESMARTPHONESUCCESS: "Smart Phone deleted successfully.",
        QUALIFIDESUCCESSMSG: "Smart Phone authorized successfully.",
        DISQUALIFIDESUCCESSMSG: "Smart Phone unauthorized successfully.",
        QUALIFIDEHEADER: "Authorize Smart Phone",
        DISQUALIFIDEHEADER: "De-authorize Smart Phone",
        QUALIFIDEBODYMSG: "Are you sure you want to authorize",
        ExistSmartPhone: "Smart Phone already exist",
        SMARTPHONELISTCOOKIES : "smartPhoneListCookies",
        DISQUALIFIDEBODYMSG: "is already authorized. Are you sure you want to de-authorize",
        SMARTPHONETYPEJSON: [{ "id": "0", "value": "Unknown", "label": "Unknown" },
        { "id": "1", "value": "Android", "label": "Android" },
        { "id": "2", "value": "Apple", "label": "Apple" }],
        ANDROIDTYPEJSON: [{ "id": "0", "value": "Android 4.1", "label": "Android 4.1" },
        { "id": "1", "value": "Android 4.2", "label": "Android 4.2" },
        { "id": "2", "value": "Android 4.3", "label": "Android 4.3" },
        { "id": "3", "value": "Android 4.4", "label": "Android 4.4" }],
        APPLETYPEJSON: [{ "id": "0", "value": "iPhone OS 1.x", "label": "iPhone OS 1.x" },
        { "id": "1", "value": "iPhone OS 2.x", "label": "iPhone OS 2.x" },
        { "id": "2", "value": "iPhone OS 3.x", "label": "iPhone OS 3.x" },
        { "id": "3", "value": "iOS 4.x", "label": "iOS 4.x" },
        { "id": "4", "value": "iOS 5.x", "label": "iOS 5.x" },
        { "id": "5", "value": "iOS 6.x", "label": "iOS 6.x" },
        { "id": "6", "value": "iOS 7.x", "label": "iOS 7.x" },
        { "id": "7", "value": "iOS 8.x", "label": "iOS 8.x" }],
        //
        LOGOUT: "Logout",
        SYSTEMSETTING: "System Settings",
        EmailInviteList : "Email Invitation List",
        VIEWAGREEMENT: "View Agreement",
        VIEWACCEPTEDEULA: "View Accepted Agreements",
        HELP: "Help",
        TOGGLENAVIGATION: "Toggle navigation",
        EVENTS: "Events",
        WORKERS: "Workers",
        CURRENTZONE: "CURRENT ZONE",
        CLOSE: "Close",
        CONTINUE: "Continue",
        ADD: "ADD",
        YES: "YES",
        NO: "NO",
        DATEFORMAT: "Date Format",
        TIMEFORMAT: "Time Format",
        DECIMAL: "Decimal",
        DEGREE: "Degree",
        //
        Administrator: "Administrator",
        READINGS: "Readings:",
        SENSORHEALTH: "Sensor Health:",
        REPORTEDZONE: "REPORTED ZONE",
        USERROLE:[
        { "id": 1, "value": "System Administrators", "label": "System Administrators" },
        { "id": 2, "value": "Administrators", "label": "Administrators" },
        { "id": 3, "value": "Advanced Users", "label": "Advanced Users" },
        { "id": 4, "value": "Worker", "label": "Worker" },
        { "id": 5, "value": "Supervisor", "label": "Supervisor" }],
        USERROLESEXTND:[
        { "id": 2, "value": "Administrators", "label": "Administrators" },
        { "id": 3, "value": "Advanced Users", "label": "Advanced Users" },
        { "id": 4, "value": "Worker", "label": "Worker" },
        { "id": 5, "value": "Supervisor", "label": "Supervisor" }],
        // ASSIGN INSTRUMENT CONSTANTS
        Product_ID: "Product ID",
        Assigned_To: "Assigned To",
        Bump_Test_Due_Date: "Bump Test Due Date",
        Assign_org: "Assign instruments to organization :",
        AllInstrument: "Total Instruments:",
        SearchVariable: "Search serial no.",
        AssignSuccessfully: "Selected instruments assigned/un-assigned successfully .",
        LoginStates: "Password updated successfully.",
        AcceptAgreement: "All agreements are accepted successfully.",
        ExpiryLink: "This link has expired.",
        Mismatch: "Password mismatch with criteria",
        //COMMON VALIDATION ERROR MESSGAES
        LOGINSPACEVALIDATION: "Spaces are not allowed",
        LOGINSPACIALCHARVALIDATION: "Allowed special characters are -_@. only",
        INTEGER: "Integer",
        MAX: "Max",
        LICENSELIMIT: " 1 to 3000",
        EMAILMAXLENGTH: 125,
        MOBILEMAXLENGTH: 15,
        MOBILEMINLENGTH: 10,
        PASSWORDLENGTH: 16,
        REQUIRED: "Required",
        ERRORMOBILE: "Mobile, Length : 10-15",
        GENERALERRORMSG: "Error in loading data",
        ERRORPOPUPCHANGESLOST: "Your changes will be lost.",
        ALLOWEDCHARACTERS: "Allowed Characters",
        ALLOWEDSPECIALCHARACTERS: "Allowed Special Characters",
        ALLCHARACTERSALLOWED: /^[^&+%]+$/,
        NOTALLOWEDCHARMSG: 'alphabet, numerals (0 through 9), and the following special characters ',
        SPACIALCHAR: "(! # $ ( ) * , - / : ; < = > ? @ [ ] ^ _ ’ { } ) are allowed.",
        DefaultAddressRegex: /^[a-zA-Z0-9_.-@#,][a-zA-Z0-9-_.,@#\s]*$/,
        OrganizationCharacterRegex: /^[a-zA-Z0-9_.-][a-zA-Z0-9-_.]*$/,
        DefaultCharacterRegex: /^[a-zA-Z0-9_.-][a-zA-Z0-9-_.\s]*$/,  // Rgex For Match .-_ only /^[a-zA-Z0-9_\.\-][a-zA-Z0-9_\.\-\s]*$/,
        UserGroupNameCharacterRegex: /^[a-zA-Z0-9_.-]+(?:[\s-,][a-zA-Z0-9-_.]+)*$/,
        REGEXALLOWSPACEBETWEENWORDS : /^[a-zA-Z0-9_.-]+( [a-zA-Z0-9_.-]+)*$/,
        OrganizationInfo : /^[a-zA-Z0-9-_.][a-zA-Z0-9_ ]*[a-zA-Z0-9-_.]*$/,
        DefaultRegexSupport: "_.-",
        AddressRegexSupport: "_.-#@,",
        DefaultMaxLength: 150,
        DefaultMinLength: 30,
        MAXPHONELENGTH: 10,
        MAXWEBLENGTH: 200,
        MAXDESCLENGTH: 300,
        MIDDLESPACEDISALLOW: /\s/,
        INVALIDCOLOR: "rgb(239, 70, 59)",
        PWDWEAKREGEX: /^[^\s]{8,}$/,
        PWDMEDIUMREGEX: /^(?=.*\d)(?=.*?[A-Z])(?=.*[a-z]).{8,16}$/,
        PWDSTRONGREGEX: /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[^a-zA-Z0-9])(?!.*\s).{8,16}$/,
        PWSALLOW: /^((?!&).)*$/,
        USERIDREGEX: /^[a-zA-Z0-9@_\-.]+$/, // /^[a-zA-Z0-9@\_\-\.]+$/,
        WEBSITEREGEX: /^(http:\/\/|https:\/\/)?([a-z0-9][a-z0-9-]*\.)+[a-z0-9][a-z0-9-]*$/, // /^(http\:\/\/|https\:\/\/)?([a-z0-9][a-z0-9\-]*\.)+[a-z0-9][a-z0-9\-]*$/,       
        USERIDALLOWEDCHARACTORS: "-_@.",
        PWDCONFIRMPWSMUSTSAME: "Confirm password must match with password",
        CONFIRMCAPTCHAERROR: "Please confirm captcha",
        ONLYALPHABETS: /^[a-zA-Z]+$/,
        ALLOWEDALPHBETSONLY: "Alphabets only",
        ONLYALPHNUMERIC: /^[a-zA-Z0-9]+$/,
        ALLOWEDALPHANUMERICONLY: "Alphanumeric Only",
        COMMUNICATIONDATEERROR: "Should be equal or greater than first communication date",
        //COMMON ERROR MESSGAES
        DEFAULTERRMSG: "Unable to get data from server. Please wait a few minutes and try again.",
        //WORKER STATUS ENUM CHECKS
        STATUSNORMAL: "Normal",
        STATUSOK: "OK",
        STATUSFAULT: "Fault",
        STATUSALARM: "Alarm",
        STATUSFAULTS: "Faults",
        STATUSALARMS: "Alarms",
        STATUSMANDOWN: "Mandown",
        STATUSPANICALARM: "Panic Alarm",
        STATUSNONCOMPLIANCE: "Non Compliance",
        WorkerStatus: {
                "WS_NORMAL": 0,
                "WS_FAULT": 1,
                "WS_ALARM": 2,
                "WS_MANDOWN": 3,
                "WS_PANIC_ALARM": 4
        },
        IMEINO: "IMEI No.",
        alarm: ["Alarm", "Mandown", "Panic Alarm"],
        alarmEnumStatus: [60, 80, 100],
        faultEnumStatus: [20],
        nonComplianceEnumStatus: [40],

        // reset password screen
        newPassword: "CREATE NEW PASSWORD",
        confirmNewPassword: "CONFIRM NEW PASSWORD",
        minimumCharacters: "Password must have a minimum of 8 characters.",
        oneCharacter: "At least one character from all of the following:",
        COBINATOPNPASSWORD: "Password must have a combination of all 4 attributes:",
        upperCase: "Upper Case",
        lowerCase: "Lower Case",
        Number: "Number: 0123456789",
        specialCharacter: "Optional Special Character: !@#$%^*()",
        strongCharacter: "Special Characters: !@#$%^*()",
        mustMatch: "Must not match last 5 passwords used.",
        // CONTACT PAGE CONTANT
        CONTACT: "Contact",
        ADDRESSBAR1: "USA - Portables",
        ADDRESSBAR2: "Honeywell Analytics Inc.",
        ADDRESSBAR3: "405 Barclay Blvd.",
        ADDRESSBAR4: "Lincolnshire, IL 60069, USA",
        MAINPHONELABLE: "Main Phone : ",
        MAINPHONE: "+1.888.749.8878",
        MAINMAILLABLE: "Main Email : ",
        MAINEMAIL: "detectgas@Honeywell.com",
        MAINFAXLABLE: "Main Fax :  ",
        MAINFAX: "+1.817.274.8321",
        HISTORICALRECORD :[
                {"id": "1", "value": "5", "label": "5 min"},
                {"id": "2", "value": "15", "label": "15 min"},
                {"id": "3", "value": "60", "label": "1 hr"},
                {"id": "4", "value": "1440", "label": "24 hr"},
                {"id": "5", "value": "custom", "label": "Custom"},
        ],

        //JSON LIST FOR COUNTRIES 
        COUNTRIESLIST:
                [
                        { "id": "1", "value": "USA (United States of America)", "label": "USA (United States of America)", "country": "USA (United States of America)" },
                        { "id": "2", "value": "Afghanistan", "label": "Afghanistan", "country": "Afghanistan" },
                        { "id": "3", "value": "Albania", "label": "Albania", "country": "Albania" },
                        { "id": "4", "value": "Algeria", "label": "Algeria", "country": "Algeria" },
                        { "id": "5", "value": "Andorra", "label": "Andorra", "country": "Andorra" },
                        { "id": "6", "value": "Angola", "label": "Angola", "country": "Angola" },
                        { "id": "7", "value": "Antigua and Barbuda", "label": "Antigua and Barbuda", "country": "Antigua and Barbuda" },
                        { "id": "8", "value": "Argentina", "label": "Argentina", "country": "Argentina" },
                        { "id": "9", "value": "Armenia", "label": "Armenia", "country": "Armenia" },
                        { "id": "10", "value": "Australia", "label": "Australia", "country": "Australia" },
                        { "id": "11", "value": "Austria", "label": "Austria", "country": "Austria" },
                        { "id": "12", "value": "Azerbaijan", "label": "Azerbaijan", "country": "Azerbaijan" },
                        { "id": "13", "value": "Bahamas", "label": "Bahamas", "country": "Bahamas" },
                        { "id": "14", "value": "Bahrain", "label": "Bahrain", "country": "Bahrain" },
                        { "id": "15", "value": "Bangladesh", "label": "Bangladesh", "country": "Bangladesh" },
                        { "id": "16", "value": "Barbados", "label": "Barbados", "country": "Barbados" },
                        { "id": "17", "value": "Belarus", "label": "Belarus", "country": "Belarus" },
                        { "id": "18", "value": "Belgium", "label": "Belgium", "country": "Belgium" },
                        { "id": "19", "value": "Belize", "label": "Belize", "country": "Belize" },
                        { "id": "20", "value": "Benin", "label": "Benin", "country": "Benin" },
                        { "id": "21", "value": "Bhutan", "label": "Bhutan", "country": "Bhutan" },
                        { "id": "22", "value": "Bolivia", "label": "Bolivia", "country": "Bolivia" },
                        { "id": "23", "value": "Bosnia and Herzegovina", "label": "Bosnia and Herzegovina", "country": "Bosnia and Herzegovina" },
                        { "id": "24", "value": "Botswana", "label": "Botswana", "country": "Botswana" },
                        { "id": "25", "value": "Brazil", "label": "Brazil", "country": "Brazil" },
                        { "id": "26", "value": "Brunei", "label": "Brunei", "country": "Brunei" },
                        { "id": "27", "value": "Bulgaria", "label": "Bulgaria", "country": "Bulgaria" },
                        { "id": "28", "value": "Burkina Faso", "label": "Burkina Faso", "country": "Burkina Faso" },
                        { "id": "29", "value": "Burundi", "label": "Burundi", "country": "Burundi" },
                        { "id": "30", "value": "Cabo Verde", "label": "Cabo Verde", "country": "Cabo Verde" },
                        { "id": "31", "value": "Cambodia", "label": "Cambodia", "country": "Cambodia" },
                        { "id": "32", "value": "Cameroon", "label": "Cameroon", "country": "Cameroon" },
                        { "id": "33", "value": "Canada", "label": "Canada", "country": "Canada" },
                        { "id": "34", "value": "Central African Republic", "label": "Central African Republic", "country": "Central African Republic" },
                        { "id": "35", "value": "Chad", "label": "Chad", "country": "Chad" },
                        { "id": "36", "value": "Chile", "label": "Chile", "country": "Chile" },
                        { "id": "37", "value": "China", "label": "China", "country": "China" },
                        { "id": "38", "value": "Colombia", "label": "Colombia", "country": "Colombia" },
                        { "id": "39", "value": "Comoros", "label": "Comoros", "country": "Comoros" },
                        { "id": "40", "value": "Congo, Republic of the", "label": "Congo, Republic of the", "country": "Congo, Republic of the" },
                        { "id": "41", "value": "Congo, Democratic Republic of the", "label": "Congo, Democratic Republic of the", "country": "Congo, Democratic Republic of the" },
                        { "id": "42", "value": "Costa Rica", "label": "Costa Rica", "country": "Costa Rica" },
                        { "id": "43", "value": "Cote d'Ivoire", "label": "Cote d'Ivoire", "country": "Cote d'Ivoire" },
                        { "id": "44", "value": "Croatia", "label": "Croatia", "country": "Croatia" },
                        { "id": "45", "value": "Cyprus", "label": "Cyprus", "country": "Cyprus" },
                        { "id": "46", "value": "Czech Republic", "label": "Czech Republic", "country": "Czech Republic" },
                        { "id": "47", "value": "Denmark", "label": "Denmark", "country": "Denmark" },
                        { "id": "48", "value": "Djibouti", "label": "Djibouti", "country": "Djibouti" },
                        { "id": "49", "value": "Dominica", "label": "Dominica", "country": "Dominica" },
                        { "id": "50", "value": "Dominican Republic", "label": "Dominican Republic", "country": "Dominican Republic" },
                        { "id": "51", "value": "Ecuador", "label": "Ecuador", "country": "Ecuador" },
                        { "id": "52", "value": "Egypt", "label": "Egypt", "country": "Egypt" },
                        { "id": "53", "value": "El Salvador", "label": "El Salvador", "country": "El Salvador" },
                        { "id": "54", "value": "Equatorial Guinea", "label": "Equatorial Guinea", "country": "Equatorial Guinea" },
                        { "id": "55", "value": "Eritrea", "label": "Eritrea", "country": "Eritrea" },
                        { "id": "56", "value": "Estonia", "label": "Estonia", "country": "Estonia" },
                        { "id": "57", "value": "Ethiopia", "label": "Ethiopia", "country": "Ethiopia" },
                        { "id": "58", "value": "Fiji", "label": "Fiji", "country": "Fiji" },
                        { "id": "59", "value": "Finland", "label": "Finland", "country": "Finland" },
                        { "id": "60", "value": "France", "label": "France", "country": "France" },
                        { "id": "61", "value": "Gabon", "label": "Gabon", "country": "Gabon" },
                        { "id": "62", "value": "Gambia", "label": "Gambia", "country": "Gambia" },
                        { "id": "63", "value": "Georgia", "label": "Georgia", "country": "Georgia" },
                        { "id": "64", "value": "Germany", "label": "Germany", "country": "Germany" },
                        { "id": "65", "value": "Ghana", "label": "Ghana", "country": "Ghana" },
                        { "id": "66", "value": "Greece", "label": "Greece", "country": "Greece" },
                        { "id": "67", "value": "Grenada", "label": "Grenada", "country": "Grenada" },
                        { "id": "68", "value": "Guatemala", "label": "Guatemala", "country": "Guatemala" },
                        { "id": "69", "value": "Guinea", "label": "Guinea", "country": "Guinea" },
                        { "id": "70", "value": "Guinea-Bissau", "label": "Guinea-Bissau", "country": "Guinea-Bissau" },
                        { "id": "71", "value": "Guyana", "label": "Guyana", "country": "Guyana" },
                        { "id": "72", "value": "Haiti", "label": "Haiti", "country": "Haiti" },
                        { "id": "73", "value": "Honduras", "label": "Honduras", "country": "Honduras" },
                        { "id": "74", "value": "Hungary", "label": "Hungary", "country": "Hungary" },
                        { "id": "75", "value": "Iceland", "label": "Iceland", "country": "Iceland" },
                        { "id": "76", "value": "India", "label": "India", "country": "India" },
                        { "id": "77", "value": "Indonesia", "label": "Indonesia", "country": "Indonesia" },
                        { "id": "78", "value": "Iraq", "label": "Iraq", "country": "Iraq" },
                        { "id": "79", "value": "Ireland", "label": "Ireland", "country": "Ireland" },
                        { "id": "80", "value": "Israel", "label": "Israel", "country": "Israel" },
                        { "id": "81", "value": "Italy", "label": "Italy", "country": "Italy" },
                        { "id": "82", "value": "Jamaica", "label": "Jamaica", "country": "Jamaica" },
                        { "id": "83", "value": "Japan", "label": "Japan", "country": "Japan" },
                        { "id": "84", "value": "Jordan", "label": "Jordan", "country": "Jordan" },
                        { "id": "85", "value": "Kazakhstan", "label": "Kazakhstan", "country": "Kazakhstan" },
                        { "id": "86", "value": "Kenya", "label": "Kenya", "country": "Kenya" },
                        { "id": "87", "value": "Kiribati", "label": "Kiribati", "country": "Kiribati" },
                        { "id": "88", "value": "Kosovo", "label": "Kosovo", "country": "Kosovo" },
                        { "id": "89", "value": "Kuwait", "label": "Kuwait", "country": "Kuwait" },
                        { "id": "90", "value": "Kyrgyzstan", "label": "Kyrgyzstan", "country": "Kyrgyzstan" },
                        { "id": "91", "value": "Laos", "label": "Laos", "country": "Laos" },
                        { "id": "92", "value": "Latvia", "label": "Latvia", "country": "Latvia" },
                        { "id": "93", "value": "Lebanon", "label": "Lebanon", "country": "Lebanon" },
                        { "id": "94", "value": "Lesotho", "label": "Lesotho", "country": "Lesotho" },
                        { "id": "95", "value": "Liberia", "label": "Liberia", "country": "Liberia" },
                        { "id": "96", "value": "Libya", "label": "Libya", "country": "Libya" },
                        { "id": "97", "value": "Liechtenstein", "label": "Liechtenstein", "country": "Liechtenstein" },
                        { "id": "98", "value": "Lithuania", "label": "Lithuania", "country": "Lithuania" },
                        { "id": "99", "value": "Luxembourg", "label": "Luxembourg", "country": "Luxembourg" },
                        { "id": "100", "value": "Macedonia", "label": "Macedonia", "country": "Macedonia" },
                        { "id": "101", "value": "Madagascar", "label": "Madagascar", "country": "Madagascar" },
                        { "id": "102", "value": "Malawi", "label": "Malawi", "country": "Malawi" },
                        { "id": "103", "value": "Malaysia", "label": "Malaysia", "country": "Malaysia" },
                        { "id": "104", "value": "Maldives", "label": "Maldives", "country": "Maldives" },
                        { "id": "105", "value": "Mali", "label": "Mali", "country": "Mali" },
                        { "id": "106", "value": "Malta", "label": "Malta", "country": "Malta" },
                        { "id": "107", "value": "Marshall Islands", "label": "Marshall Islands", "country": "Marshall Islands" },
                        { "id": "108", "value": "Mauritania", "label": "Mauritania", "country": "Mauritania" },
                        { "id": "109", "value": "Mauritius", "label": "Mauritius", "country": "Mauritius" },
                        { "id": "110", "value": "Mexico", "label": "Mexico", "country": "Mexico" },
                        { "id": "111", "value": "Micronesia", "label": "Micronesia", "country": "Micronesia" },
                        { "id": "112", "value": "Moldova", "label": "Moldova", "country": "Moldova" },
                        { "id": "113", "value": "Monaco", "label": "Monaco", "country": "Monaco" },
                        { "id": "114", "value": "Mongolia", "label": "Mongolia", "country": "Mongolia" },
                        { "id": "115", "value": "Montenegro", "label": "Montenegro", "country": "Montenegro" },
                        { "id": "116", "value": "Morocco", "label": "Morocco", "country": "Morocco" },
                        { "id": "117", "value": "Mozambique", "label": "Mozambique", "country": "Mozambique" },
                        { "id": "118", "value": "Myanmar (Burma)", "label": "Myanmar (Burma)", "country": "Myanmar (Burma)" },
                        { "id": "119", "value": "Namibia", "label": "Namibia", "country": "Namibia" },
                        { "id": "120", "value": "Nauru", "label": "Nauru", "country": "Nauru" },
                        { "id": "121", "value": "Nepal", "label": "Nepal", "country": "Nepal" },
                        { "id": "122", "value": "Netherlands", "label": "Netherlands", "country": "Netherlands" },
                        { "id": "123", "value": "New Zealand", "label": "New Zealand", "country": "New Zealand" },
                        { "id": "124", "value": "Nicaragua", "label": "Nicaragua", "country": "Nicaragua" },
                        { "id": "125", "value": "Niger", "label": "Niger", "country": "Niger" },
                        { "id": "126", "value": "Nigeria", "label": "Nigeria", "country": "Nigeria" },
                        { "id": "127", "value": "Norway", "label": "Norway", "country": "Norway" },
                        { "id": "128", "value": "Oman", "label": "Oman", "country": "Oman" },
                        { "id": "129", "value": "Pakistan", "label": "Pakistan", "country": "Pakistan" },
                        { "id": "130", "value": "Palau", "label": "Palau", "country": "Palau" },
                        { "id": "131", "value": "Palestine", "label": "Palestine", "country": "Palestine" },
                        { "id": "132", "value": "Panama", "label": "Panama", "country": "Panama" },
                        { "id": "133", "value": "Papua New Guinea", "label": "Papua New Guinea", "country": "Papua New Guinea" },
                        { "id": "134", "value": "Paraguay", "label": "Paraguay", "country": "Paraguay" },
                        { "id": "135", "value": "Peru", "label": "Peru", "country": "Peru" },
                        { "id": "136", "value": "Philippines", "label": "Philippines", "country": "Philippines" },
                        { "id": "137", "value": "Poland", "label": "Poland", "country": "Poland" },
                        { "id": "138", "value": "Portugal", "label": "Portugal", "country": "Portugal" },
                        { "id": "139", "value": "Qatar", "label": "Qatar", "country": "Qatar" },
                        { "id": "140", "value": "Romania", "label": "Romania", "country": "Romania" },
                        { "id": "141", "value": "Russia", "label": "Russia", "country": "Russia" },
                        { "id": "142", "value": "Rwanda", "label": "Rwanda", "country": "Rwanda" },
                        { "id": "143", "value": "St. Kitts and Nevis", "label": "St. Kitts and Nevis", "country": "St. Kitts and Nevis" },
                        { "id": "144", "value": "St. Lucia", "label": "St. Lucia", "country": "St. Lucia" },
                        { "id": "145", "value": "St. Vincent and The Grenadines", "label": "St. Vincent and The Grenadines", "country": "St. Vincent and The Grenadines" },
                        { "id": "146", "value": "Samoa", "label": "Samoa", "country": "Samoa" },
                        { "id": "147", "value": "San Marino", "label": "San Marino", "country": "San Marino" },
                        { "id": "148", "value": "Sao Tome and Principe", "label": "Sao Tome and Principe", "country": "Sao Tome and Principe" },
                        { "id": "149", "value": "Saudi Arabia", "label": "Saudi Arabia", "country": "Saudi Arabia" },
                        { "id": "150", "value": "Senegal", "label": "Senegal", "country": "Senegal" },
                        { "id": "151", "value": "Serbia", "label": "Serbia", "country": "Serbia" },
                        { "id": "152", "value": "Seychelles", "label": "Seychelles", "country": "Seychelles" },
                        { "id": "153", "value": "Sierra Leone", "label": "Sierra Leone", "country": "Sierra Leone" },
                        { "id": "154", "value": "Singapore", "label": "Singapore", "country": "Singapore" },
                        { "id": "155", "value": "Slovakia", "label": "Slovakia", "country": "Slovakia" },
                        { "id": "156", "value": "Slovenia", "label": "Slovenia", "country": "Slovenia" },
                        { "id": "157", "value": "Solomon Islands", "label": "Solomon Islands", "country": "Solomon Islands" },
                        { "id": "158", "value": "Somalia", "label": "Somalia", "country": "Somalia" },
                        { "id": "159", "value": "South Africa", "label": "South Africa", "country": "South Africa" },
                        { "id": "160", "value": "South Korea", "label": "South Korea", "country": "South Korea" },
                        { "id": "161", "value": "South Sudan", "label": "South Sudan", "country": "South Sudan" },
                        { "id": "162", "value": "Spain", "label": "Spain", "country": "Spain" },
                        { "id": "162", "value": "Sri Lanka", "label": "Sri Lanka", "country": "Sri Lanka" },
                        { "id": "164", "value": "Suriname", "label": "Suriname", "country": "Suriname" },
                        { "id": "165", "value": "Swaziland", "label": "Swaziland", "country": "Swaziland" },
                        { "id": "166", "value": "Sweden", "label": "Sweden", "country": "Sweden" },
                        { "id": "167", "value": "Switzerland", "label": "Switzerland", "country": "Switzerland" },
                        { "id": "168", "value": "Taiwan", "label": "Taiwan", "country": "Taiwan" },
                        { "id": "169", "value": "Tajikistan", "label": "Tajikistan", "country": "Tajikistan" },
                        { "id": "170", "value": "Tanzania", "label": "Tanzania", "country": "Tanzania" },
                        { "id": "171", "value": "Thailand", "label": "Thailand", "country": "Thailand" },
                        { "id": "172", "value": "Timor-Leste", "label": "Timor-Leste", "country": "Timor-Leste" },
                        { "id": "173", "value": "Togo", "label": "Togo", "country": "Togo" },
                        { "id": "174", "value": "Tonga", "label": "Tonga", "country": "Tonga" },
                        { "id": "175", "value": "Trinidad and Tobago", "label": "Trinidad and Tobago", "country": "Trinidad and Tobago" },
                        { "id": "176", "value": "Tunisia", "label": "Tunisia", "country": "Tunisia" },
                        { "id": "177", "value": "Turkey", "label": "Turkey", "country": "Turkey" },
                        { "id": "178", "value": "Turkmenistan", "label": "Turkmenistan", "country": "Turkmenistan" },
                        { "id": "179", "value": "Tuvalu", "label": "Tuvalu", "country": "Tuvalu" },
                        { "id": "180", "value": "Uganda", "label": "Uganda", "country": "Uganda" },
                        { "id": "181", "value": "Ukraine", "label": "Ukraine", "country": "Ukraine" },
                        { "id": "182", "value": "United Arab Emirates", "label": "United Arab Emirates", "country": "United Arab Emirates" },
                        { "id": "183", "value": "UK (United Kingdom)", "label": "UK (United Kingdom)", "country": "UK (United Kingdom)" },
                        { "id": "184", "value": "Uruguay", "label": "Uruguay", "country": "Uruguay" },
                        { "id": "185", "value": "Uzbekistan", "label": "Uzbekistan", "country": "Uzbekistan" },
                        { "id": "186", "value": "Vanuatu", "label": "Vanuatu", "country": "Vanuatu" },
                        { "id": "187", "value": "Vatican City (Holy See)", "label": "Vatican City (Holy See)", "country": "Vatican City (Holy See)" },
                        { "id": "188", "value": "Venezuela", "label": "Venezuela", "country": "Venezuela" },
                        { "id": "189", "value": "Vietnam", "label": "Vietnam", "country": "Vietnam" },
                        { "id": "190", "value": "Yemen", "label": "Yemen", "country": "Yemen" },
                        { "id": "191", "value": "Zambia", "label": "Zambia", "country": "Zambia" },
                        { "id": "192", "value": "Zimbabwe", "label": "Zimbabwe", "country": "Zimbabwe" },
                ],
        USSTATELIST: [
                { "id": "1", "value": "Alabama", "label": "Alabama", "state": "Alabama" },
                { "id": "2", "value": "Alaska", "label": "Alaska", "state": "Alaska" },
                { "id": "3", "value": "Arizona", "label": "Arizona", "state": "Arizona" },
                { "id": "4", "value": "Arkansas", "label": "Arkansas", "state": "Arkansas" },
                { "id": "5", "value": "California", "label": "California", "state": "California" },
                { "id": "6", "value": "Colorado", "label": "Colorado", "state": "Colorado" },
                { "id": "7", "value": "Connecticut", "label": "Connecticut", "state": "Connecticut" },
                { "id": "8", "value": "Delaware", "label": "Delaware", "state": "Delaware" },
                { "id": "9", "value": "Florida", "label": "Florida", "state": "Florida" },
                { "id": "10", "value": "Georgia", "label": "Georgia", "state": "Georgia" },
                { "id": "11", "value": "Hawaii", "label": "Hawaii", "state": "Hawaii" },
                { "id": "12", "value": "Idaho", "label": "Idaho", "state": "Idaho" },
                { "id": "13", "value": "Illinois", "label": "Illinois", "state": "Illinois" },
                { "id": "14", "value": "Indiana", "label": "Indiana", "state": "Indiana" },
                { "id": "15", "value": "Iowa", "label": "Iowa", "state": "Iowa" },
                { "id": "16", "value": "Kansas", "label": "Kansas", "state": "Kansas" },
                { "id": "17", "value": "Kentucky", "label": "Kentucky", "state": "Kentucky" },
                { "id": "18", "value": "Louisiana", "label": "Louisiana", "state": "Louisiana" },
                { "id": "19", "value": "Maine", "label": "Maine", "state": "Maine" },
                { "id": "20", "value": "Maryland", "label": "Maryland", "state": "Maryland" },
                { "id": "21", "value": "Massachusetts", "label": "Massachusetts", "state": "Massachusetts" },
                { "id": "22", "value": "Michigan", "label": "Michigan", "state": "Michigan" },
                { "id": "23", "value": "Minnesota", "label": "Minnesota", "state": "Minnesota" },
                { "id": "24", "value": "Mississippi", "label": "Mississippi", "state": "Mississippi" },
                { "id": "25", "value": "Missouri", "label": "Missouri", "state": "Missouri" },
                { "id": "26", "value": "Montana", "label": "Montana", "state": "Montana" },
                { "id": "27", "value": "Nebraska", "label": "Nebraska", "state": "Nebraska" },
                { "id": "28", "value": "Nevada", "label": "Nevada", "state": "Nevada" },
                { "id": "29", "value": "New Hampshire", "label": "New Hampshire", "state": "New Hampshire" },
                { "id": "30", "value": "New Jersey", "label": "New Jersey", "state": "New Jersey" },
                { "id": "31", "value": "New Mexico", "label": "New Mexico", "state": "New Mexico" },
                { "id": "32", "value": "New York", "label": "New York", "state": "New York" },
                { "id": "33", "value": "North Carolina", "label": "North Carolina", "state": "North Carolina" },
                { "id": "34", "value": "North Dakota", "label": "North Dakota", "state": "North Dakota" },
                { "id": "35", "value": "Ohio", "label": "Ohio", "state": "Ohio" },
                { "id": "36", "value": "Oklahoma", "label": "Oklahoma", "state": "Oklahoma" },
                { "id": "37", "value": "Oregon", "label": "Oregon", "state": "Oregon" },
                { "id": "38", "value": "Pennsylvania", "label": "Pennsylvania", "state": "Pennsylvania" },
                { "id": "39", "value": "Rhode Island", "label": "Rhode Island", "state": "Rhode Island" },
                { "id": "40", "value": "South Carolina", "label": "South Carolina", "state": "South Carolina" },
                { "id": "41", "value": "South Dakota", "label": "South Dakota", "state": "South Dakota" },
                { "id": "42", "value": "Tennessee", "label": "Tennessee", "state": "Tennessee" },
                { "id": "43", "value": "Texas", "label": "Texas", "state": "Texas" },
                { "id": "44", "value": "Utah", "label": "Utah", "state": "Utah" },
                { "id": "45", "value": "Vermont", "label": "Vermont", "state": "Vermont" },
                { "id": "46", "value": "Virginia", "label": "Virginia", "state": "Virginia" },
                { "id": "47", "value": "Washington", "label": "Washington", "state": "Washington" },
                { "id": "48", "value": "West Virginia", "label": "West Virginia", "state": "West Virginia" },
                { "id": "49", "value": "Wisconsin", "label": "Wisconsin", "state": "Wisconsin" },
                { "id": "50", "value": "Wyoming", "label": "Wyoming", "state": "Wyoming" },
        ],
        INDUSTRIESLIST:[
                { "id": "1", "value": "Industrial", "label": "Industrial" },
                { "id": "2", "value": "Fire & Hazmat", "label": "Fire & Hazmat" },
                { "id": "3", "value": "Environmental", "label": "Environmental" },
                { "id": "4", "value": "Nation Security", "label": "Nation Security" },
                { "id": "5", "value": "Oil & Gas", "label": "Oil & Gas" },
        ],
        ALARMCATS: { "Sensor": "sensor", "Device": "device", "User": "User" },
        DEVICEALARMSTATUS: ["Mandown Warning", "Mandown Alarm", "Super Alarm", "Panic Alarm"],
        SENSORFAULTSTATUS: ["Lamp", "Off", "Short", "Broken", "Fail"],
        RTMURLLINKS: ["mapview", "events", "worker"],
        RoleNotApplicable: [4, 5, 6, 8, 10, 11],
        RoleApplicable: [1, 2, 3, 7, 9],
        SuperAdministrator: "System Administrators",
        ADMINISTRATORSROLE: "Administrators",
        AdvanceUser: "Advanced Users",
        Worker: "Worker",
        Supervisor: "Supervisor",
        //COMMON CONSTANTS 
        ZERO: 0,
       DocErrorCode: 10010,
        ONE: 1,
        TWO: 2,
        TEN: 10,
        DefaultAgreementList : [1,4,5],
        SystemSettingsDocsList : [1,2,3,4,5],
        OtherOrgAgreementList : [1,6,7],
        EXCEPTIONMSG: "There is an error detected, please try reloading the page.",
        TWOKINTERVAl : 2000,
        EXPIRYPSDMSG : "As per the password policy, your current password has expired.",
        CONFIRM:"Confirm",
        //GET WORKER LIST COUNT API PARMAS
        WORKERCOUNTSORTCOLUMN: 1,
        WORKERCOUNTSORTORDER: true,
        WORKERCOUNTREQUIEDBASICINFO: false,
        WORKERCOUNTREQUIREDCOUNT: 0,
        WORKERCOUNTSTARTINDEX: 0,
        DEFAULTMAPCOUNTTIMEOUT: 5000,
        // COUNT STORAGE VARIABLES
        STORETOTALWORKER: "totalWorker",
        STOREONLINEWORKER: "onlineWorker",
        STOREALARMWORKER: "workerInAlarm",
        STOREFAULTWORKER: "workerInFault",
        STORENONCOMPLIANCEWORKER: "nonCompliance",
        // ALL ERRORCODES JSON
        Errorcode: [{"ErrorCode":21001,"ErrorMessage":"Unknown User."},{"ErrorCode":21002,"ErrorMessage":"Username or Password is incorrect."},{"ErrorCode":21004,"ErrorMessage":"Username or Password is incorrect."},{"ErrorCode":21006,"ErrorMessage":"User has no privilege to login."},{"ErrorCode":21007,"ErrorMessage":"Username or Password is incorrect."},{"ErrorCode":20005,"ErrorMessage":"The SC count is full of this organization"},{"ErrorCode":20004,"ErrorMessage":"User Organization has been expired."},{"ErrorCode":20006,"ErrorMessage":"Approval Pending"},{"ErrorCode":20007,"ErrorMessage":"Access Denied"},{"ErrorCode":20009,"ErrorMessage":"Offline payment pending"}, {"ErrorCode":20010,"ErrorMessage":"Organization Deactivated"}],
        //Required Count
        TOTALREQUIREDCOUNTS:"10000",
        OUTERPAGES: ["Login", "Eula", "ResetPassword", "ChangePassword", "ForgotPassword", "LockedAccount", "contact", "privacy", "Logout", "LinkExpire", "SignUp", "TrialAccount", "PaidAccount","Changeresetpassword","changeresetpassword","eula","signup","privacy","contact"],
        RTMPAGES:["mapview","events","worker"],
        //userolesandvalues
        SYSTEMADMINISTRATORROLE: "1",
        ADMINISTRATORROLE: "2",
        ADVANCEUSERROLE: "3",
        SUPERVISORROLE: "4",
        WORKERROLE: "5",
        //userolesandvalues
        KeepSignIn: "AuthToken",
        cookieNotExist: "Cookie not exist",
        cookieMod: "Cookie modified",
        PSWDLINKEXPIRYHOURS: 2,
        LINKEXPIRTITLE: "Link Expired",
        SideBarAssignPopHeight: 220,
        TabAssignPopHeight: 110,
        //  FEEDBACK VARIABLES
        USERFEEDBACK: "User Feedback",
        FEEDBACK: "Feedback",
        FEEDBACKSUCCESS: "Feedback submitted successfully.",
        FEEDBACKFAILED: "Error while submitting",
        ADDFEEDBACKURL: "<br />User had given the feedback from -",
        Session_Timeout: "Session_Timeout",
        TRYRELOAD: "Try ReLoad",
        PRIVATEBROWSINGWARNING: "Browser is running in Private Mode. Application will not work properly. Please turn off the Private Browsing mode.",
        WARNINGTITLE: "Warning",
        MAPHEIGHT: "calc(100vh - 52px)",
        //cookies
        EVENTFILTER:"eventsFilter",
        HISTORICALEVENTFILTER:"historicalEventsFilter",
        HISTORICALWORKERACCOUNTCOOKIES : "historicalworkerAccountCookies",
        WORKERACCOUNTCOOKIES:"workerAccountCookies",
        WORKERSTARTTIMECOOKIES:"startTime",
        WORKERENDTIMECOOKIES:"endTime",
        WORKERFILTERCOOKIES:"workerFilterCookies",
        WORKERFULLNAMECOOKIES:"workerFullNameCookies",
        name:"NAME",
        address:"ADDRESS",
        expirydate:"EXPIRY DATE",
        createddate:"CREATED DATE",
        contactperson:"CONTACT PERSON",
        // Toast messages
        Success: "Success",
        Error: "Error",
        Warning: "Warning",
        Info: "Info",
        stateRegex:/^[a-zA-Z0-9\s .-]*$/,
        organizationRegex:/^[a-zA-Z0-9\s]*$/,
        AddressRegex:/^[a-zA-Z0-9\s .*-/+@!#%^*()$]*$/,
        alphaNumericRegex:/^[a-zA-Z0-9\s]*$/,
        MobileNumberRegex:/^(\+\d{1,3}[- ]?)?\d{10,15}$|^$/,
        WebsiteRegex:/^((https?|ftp|smtp):\/\/)?(www.)?[a-z0-9]+\.[a-z]+(\/[a-zA-Z0-9#]+\/?)*$|^$/,
        LicenseCountRegex:/^([1-9]|[1-8][0-9]|9[0-9]|[1-8][0-9]{2}|9[0-8][0-9]|99[0-9]|[12][0-9]{3}|3000)$/,
        EmailRegex:/^(("[\w-\s]+")|([\w-]+(?:\.[\w-]+)*)|("[\w-\s]+")([\w-]+(?:\.[\w-]+)*))(@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$)|(@\[?((25[0-5]\.|2[0-4][0-9]\.|1[0-9]{2}\.|[0-9]{1,2}\.))((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\.){2}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\]?$)/i,
        passwordRegex:/^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\$%\^&\*])(?=.{8,})/,
        constOrgName:{"id": "1", "value": "Default", "label": "Default", "country": "Default"},
        constUserGroup:{"id": "1", "value": "Group A", "label": "Group A", "country": "Group A"},
        constHistoricalRecord:{"id": "1", "value": "5 min", "label": "5 min", "country": "5 min"},
        constCountry:{ "id": "1", "value": "USA (United States of America)", "label": "USA (United States of America)", "country": "USA (United States of America)" },
        constOrg:{ id: "1", value: "Administrator", label: "Administrator" },
        ImgExtensionValidation:"Please Upload File Having extensions .JPEG/.JPG/.PNG/.GIF only.",
        ImgSizeValidation:"File Size Exceeds 1 MB",
        newpasswordLabel:"[New Password]",
        confirmpasswordLabel:"[Confirm Password]",
        defaultImg:"/images/upload.jpg",

        //Default Options
        defaultOrg : "Default",
        defaultCountry : "India",
        

        //ErrorMessage
        dateErrorMessage:"Should be greater than current date",
        HAVEANACCOUNT : "Already have an account.",
        UserGroup:[
                {"id": "1", "value": "Group A", "label": "Group A" },
                {"id": "2", "value": "Group B", "label": "Group B"},
                // {"id": "3", "value": "Group C", "label": "Group C"},
                // {"id": "4", "value": "Group D", "label": "Group D"},
                // {"id": "5", "value": "Group E", "label": "Group E"},
                // {"id": "6", "value": "Group F", "label": "Group F"}
                ],
        custom : "custom",
        CustomRange : "CUSTOM"
};
export default messages;
